- alias: homeassistant_start
  id: man0001
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.automatisk_lys
      
- alias: modeset
  id: man0002
  trigger:
    - platform: state
      entity_id:
        - input_boolean.home
        - input_boolean.away
        - input_boolean.goodnight
        - input_boolean.goodmorning
      to: "on"
    - platform: state
      entity_id:
        - input_boolean.full_house
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: >
          {%if { trigger.entity_id } is input_boolean.home %}
            - input_boolean.away
          {%elif { trigger.entity_id } is input_boolean.away %}
            - input_boolean.home
          {%elif { trigger.entity_id } is input_boolean.goodnight %}
            - input_boolean.goodmorning
          {%elif { trigger.entity_id } is input_boolean.goodmorning %}
            - input_boolean.goodnight
          {%endif%}
    - service: input_select.select_option
      data_template: >
        {%if { trigger.entity_id } is input_boolean.goodmorning %}
          entity_id: input_select.timeofday
          option: "Dag"
        {%elif { trigger.entity_id } is input_boolean.goodnight %}
          entity_id: input_select.timeofday
          option: "Natt"
        {%elif { trigger.entity_id } is input_boolean.away %}
          entity_id: input_select.home_status
          option: "Borte"
        {%elif { trigger.entity_id } is input_boolean.home %}
          {%if state.input_boolean.full_house is "on" %}
            entity_id: input_select.home_status
            option: "Fullt hus"
          {%elif state.input_boolean.full_house is "off" %}
            entity_id: input_select.home_status
            option: "Normal"
          {%endif%}
        {%endif%}