- alias: homeassistant_start
  id: man0001
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.automatisk_lys

- alias: modeset
  id: man0002
  trigger:
    - platform: state
      entity_id:
        - input_boolean.home
        - input_boolean.away
        - input_boolean.goodnight
        - input_boolean.goodmorning
      to: "on"
    - platform: state
      entity_id:
        - input_boolean.full_house
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: >
          {%if trigger.entity_id == "input_boolean.home" %}
            input_boolean.away
          {%elif trigger.entity_id == "input_boolean.away" %}
            input_boolean.home
          {%elif trigger.entity_id == "input_boolean.goodnight" %}
            input_boolean.goodmorning
          {%elif trigger.entity_id == "input_boolean.goodmorning" %}
            input_boolean.goodnight
          {%endif%}
    - service: input_select.select_option
      data_template:
        entity_id: >
          {%if trigger.entity_id == "input_boolean.goodmorning" or trigger.entity_id == "input_boolean.goodnight" %}
            input_select.timeofday
          {%else%}
            input_select.home_status
          {%endif%}
        option: >
          {%if trigger.entity_id == "input_boolean.goodmorning" %}
            Dag
          {%elif trigger.entity_id == "input_boolean.goodnight" %}
            Natt
          {%elif trigger.entity_id == "input_boolean.away" %}
            Borte
          {%elif trigger.entity_id == "input_boolean.home" and is_state("input_boolean.full_house", "on") %}
            Fullt Hus
          {%elif trigger.entity_id == "input_boolean.full_house" and input_boolean.full_house == "on" %}
            Fullt Hus
          {%elif trigger.entity_id == "input_boolean.home" and is_state("input_boolean.full_house", "off") %}
            Normal
          {%elif trigger.entity_id == "input_boolean.full_house" and input_boolean.full_house == "off" %}
            Normal
          {%endif%}
