# - alias: homeassistant_start
#   id: man0001
#   trigger:
#     platform: homeassistant
#     event: start
#   action:
#     - service: switch.turn_on
#       data:
#         entity_id: switch.automatisk_lys
- alias: flux
  id: man0001
  trigger:
    - platform: time_pattern
      minutes: '/30'
    - platform: state
      entity_id: input_select.home_status
    - platform: state
      entity_id: input_select.timeofday
  action:
    - service: switch.automatisk_lys_update

- alias: modeset
  id: man0002
  trigger:
    - platform: state
      entity_id:
        - input_boolean.homemode
        - input_boolean.awaymode
        - input_boolean.nightmode
        - input_boolean.daymode
      to: "on"
    - platform: state
      entity_id:
        - input_boolean.full_house
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: >
          {%if trigger.entity_id == "input_boolean.homemode" %}
            input_boolean.awaymode
          {%elif trigger.entity_id == "input_boolean.awaymode" %}
            input_boolean.homemode
          {%elif trigger.entity_id == "input_boolean.nightmode" %}
            input_boolean.daymode
          {%elif trigger.entity_id == "input_boolean.daymode" %}
            input_boolean.nightmode
          {%endif%}
    - service: input_select.select_option
      data_template:
        entity_id: >
          {%if trigger.entity_id == "input_boolean.daymode" or trigger.entity_id == "input_boolean.nightmode" %}
            input_select.timeofday
          {%else%}
            input_select.home_status
          {%endif%}
        option: >
          {%if trigger.entity_id == "input_boolean.daymode" %}
            Dag
          {%elif trigger.entity_id == "input_boolean.nightmode" %}
            Natt
          {%elif trigger.entity_id == "input_boolean.awaymode" %}
            Borte
          {%elif trigger.entity_id == "input_boolean.homemode" and is_state("input_boolean.full_house", "on") %}
            Fullt Hus
          {%elif trigger.entity_id == "input_boolean.full_house" and is_state("input_boolean.full_house", "on") %}
            Fullt Hus
          {%elif trigger.entity_id == "input_boolean.homemode" and is_state("input_boolean.full_house", "off") %}
            Normal
          {%elif trigger.entity_id == "input_boolean.full_house" and is_state("input_boolean.full_house", "off") %}
            Normal
          {%endif%}

- alias: moderun
  id: man0003
  trigger:
    - platform: state
      entity_id:
        - input_select.home_status
        - input_select.timeofday
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {%if is_state("input_select.home_status", "Fullt Hus") and is_state("input_select.timeofday", "Dag") %}
            script.mode_home_day_full_house
          {%elif is_state("input_select.home_status", "Normal") and is_state("input_select.timeofday", "Dag") %}
            script.mode_home_day_normal
          {%elif is_state("input_select.home_status", "Fullt Hus") and is_state("input_select.timeofday", "Natt") %}
            script.mode_home_night_full_house
          {%elif is_state("input_select.home_status", "Normal")and is_state("input_select.timeofday", "Natt") %}
            script.mode_home_night_full_house
          {%elif is_state("input_select.home_status", "Borte")%}
            script.mode_away
          {%endif%}

- alias: restart_home
  id: man0004
  trigger:
    - entity: light.taklampe_entre
      to: 'Unavailable'
  action:
    - service: script.restart_home
    # - service: notify.notify_jostein
    #   data:
    #     message: Homeserver restarted
