- platform: flux
  name: Automatisk lys
  lights:
    - light.gang
    - light.stue
    - light.kjkken
    - light.lekestue
  start_time: '7:00'
  stop_time: '23:00'
  start_colortemp: 4400
  sunset_colortemp: 4000
  stop_colortemp: 3500
#  brightness: 200
  disable_brightness_adjust: False
  mode: rgb
  transition: 30
  interval: 30