- platform: flux
  name: Automatisk lys
  lights:
    - light.gang
    - light.stue
    - light.kjkken

  start_time: '7:00'
  stop_time: '23:00'
  start_colortemp: 3500
  sunset_colortemp: 2500
  stop_colortemp: 1000
#  brightness: 200
  disable_brightness_adjust: False
  mode: xy
  transition: 30
  interval: 60