- platform: flux
  name: Automatisk lys
  lights:
    - light.gang
    - light.stue
    - light.kjkken
    - light.lekestue
  start_time: '7:00'
  stop_time: '23:00'
  start_colortemp: 4400
  sunset_colortemp: 3000 
  stop_colortemp: 1000
#  brightness: 200
  disable_brightness_adjust: False
  mode: mired
  transition: 30
  interval: 30