- platform: flux
  name: Automatisk lys
  lights:
    - light.gang
    - light.stue
    - light.kjkken

  start_time: '7:00'
  stop_time: '23:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 2200
#  brightness: 200
  disable_brightness_adjust: False
  mode: xy
  transition: 30
  interval: 60